name: cheonjiyeon_app
description: Cheonjiyeon Lotus Shrine mobile app
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  permission_handler: ^11.3.0
  connectivity_plus: ^6.0.3

flutter:
  uses-material-design: true
